# Generated by Django 4.2.6 on 2023-10-11 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspeciePez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'especie_pez',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('feinicio', models.DateField()),
                ('fefinal', models.DateField()),
                ('especies', models.CharField(max_length=150)),
                ('cantpeces', models.IntegerField()),
                ('alimentacion', models.CharField(max_length=150)),
                ('frecualimentacion', models.CharField(max_length=150)),
                ('tiemcultivo', models.IntegerField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.cultivo')),
                ('especie_pez', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='piscicultura.especiepez')),
            ],
            options={
                'db_table': 'estanque',
                'managed': True,
            },
        ),
    ]
