# Generated by Django 4.2.6 on 2023-10-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
