# Generated by Django 4.2.6 on 2023-10-11 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_cultivo_created_at_cultivo_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiptrata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tiptrata',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tsensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tsensor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('dosis', models.FloatField()),
                ('resultado', models.CharField(max_length=250)),
                ('tipo_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.tiptrata')),
            ],
            options={
                'db_table': 'tratamiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=150)),
                ('tipo_sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.tsensor')),
            ],
            options={
                'db_table': 'sensor',
                'managed': True,
            },
        ),
    ]
