# Generated by Django 4.2.6 on 2023-10-10 21:00

from django.db import migrations

def t_identificacion_inserts(apps, schema_editor):
    with open('./sql/tidentificacion.sql', 'r',encoding='utf-8') as sql_file:
        sql_query = sql_file.read()
    
    # Ejecuta la consulta SQL
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(sql_query)
class Migration(migrations.Migration):

    dependencies = [
        ('empabee_auth', '0002_auto_20231010_1543'),
    ]

    operations = [
        migrations.RunPython(t_identificacion_inserts),
    ]
