INSERT INTO `pais` (`code`, `iso3166a1`, `iso3166a2`, `nombre`, `created_at`, `updated_at`) 
VALUES 
(4, 'AF', 'AFG', 'Afganistán', NOW(), NOW()),
(248, 'AX', 'ALA', 'Islas Gland',NOW(), NOW()),
(8, 'AL', 'ALB', 'Albania',NOW(), NOW()),
(276, 'DE', 'DEU', 'Alemania',NOW(), NOW()),
(20, 'AD', 'AND', 'Andorra',NOW(), NOW()),
(24, 'AO', 'AGO', 'Angola',NOW(), NOW()),
(660, 'AI', 'AIA', 'Anguilla',NOW(), NOW()),
(10, 'AQ', 'ATA', 'Antártida',NOW(), NOW()),
(28, 'AG', 'ATG', 'Antigua y Barbuda',NOW(), NOW()),
(530, 'AN', 'ANT', 'Antillas Holandesas',NOW(), NOW()),
(682, 'SA', 'SAU', 'Arabia Saudí',NOW(), NOW()),
(12, 'DZ', 'DZA', 'Argelia',NOW(), NOW()),
(32, 'AR', 'ARG', 'Argentina',NOW(), NOW()),
(51, 'AM', 'ARM', 'Armenia',NOW(), NOW()),
(533, 'AW', 'ABW', 'Aruba',NOW(), NOW()),
(36, 'AU', 'AUS', 'Australia',NOW(), NOW()),
(40, 'AT', 'AUT', 'Austria',NOW(), NOW()),
(31, 'AZ', 'AZE', 'Azerbaiyán',NOW(), NOW()),
(44, 'BS', 'BHS', 'Bahamas',NOW(), NOW()),
(48, 'BH', 'BHR', 'Bahréin',NOW(), NOW()),
(50, 'BD', 'BGD', 'Bangladesh',NOW(), NOW()),
(52, 'BB', 'BRB', 'Barbados',NOW(), NOW()),
(112, 'BY', 'BLR', 'Bielorrusia',NOW(), NOW()),
(56, 'BE', 'BEL', 'Bélgica',NOW(), NOW()),
(84, 'BZ', 'BLZ', 'Belice',NOW(), NOW()),
(204, 'BJ', 'BEN', 'Benin',NOW(), NOW()),
(60, 'BM', 'BMU', 'Bermudas',NOW(), NOW()),
(64, 'BT', 'BTN', 'Bhután',NOW(), NOW()),
(68, 'BO', 'BOL', 'Bolivia',NOW(), NOW()),
(70, 'BA', 'BIH', 'Bosnia y Herzegovina',NOW(), NOW()),
(72, 'BW', 'BWA', 'Botsuana',NOW(), NOW()),
(74, 'BV', 'BVT', 'Isla Bouvet',NOW(), NOW()),
(76, 'BR', 'BRA', 'Brasil',NOW(), NOW()),
(96, 'BN', 'BRN', 'Brunéi',NOW(), NOW()),
(100, 'BG', 'BGR', 'Bulgaria',NOW(), NOW()),
(854, 'BF', 'BFA', 'Burkina Faso',NOW(), NOW()),
(108, 'BI', 'BDI', 'Burundi',NOW(), NOW()),
(132, 'CV', 'CPV', 'Cabo Verde',NOW(), NOW()),
(136, 'KY', 'CYM', 'Islas Caimán',NOW(), NOW()),
(116, 'KH', 'KHM', 'Camboya',NOW(), NOW()),
(120, 'CM', 'CMR', 'Camerún',NOW(), NOW()),
(124, 'CA', 'CAN', 'Canadá',NOW(), NOW()),
(140, 'CF', 'CAF', 'República Centroafricana',NOW(), NOW()),
(148, 'TD', 'TCD', 'Chad',NOW(), NOW()),
(203, 'CZ', 'CZE', 'República Checa',NOW(), NOW()),
(152, 'CL', 'CHL', 'Chile',NOW(), NOW()),
(156, 'CN', 'CHN', 'China',NOW(), NOW()),
(196, 'CY', 'CYP', 'Chipre',NOW(), NOW()),
(162, 'CX', 'CXR', 'Isla de Navidad',NOW(), NOW()),
(336, 'VA', 'VAT', 'Ciudad del Vaticano',NOW(), NOW()),
(166, 'CC', 'CCK', 'Islas Cocos',NOW(), NOW()),
(170, 'CO', 'COL', 'Colombia',NOW(), NOW()),
(174, 'KM', 'COM', 'Comoras',NOW(), NOW()),
(180, 'CD', 'COD', 'República Democrática del Congo',NOW(), NOW()),
(178, 'CG', 'COG', 'Congo',NOW(), NOW()),
(184, 'CK', 'COK', 'Islas Cook',NOW(), NOW()),
(408, 'KP', 'PRK', 'Corea del Norte',NOW(), NOW()),
(410, 'KR', 'KOR', 'Corea del Sur',NOW(), NOW()),
(384, 'CI', 'CIV', 'Costa de Marfil',NOW(), NOW()),
(188, 'CR', 'CRI', 'Costa Rica',NOW(), NOW()),
(191, 'HR', 'HRV', 'Croacia',NOW(), NOW()),
(192, 'CU', 'CUB', 'Cuba',NOW(), NOW()),
(208, 'DK', 'DNK', 'Dinamarca',NOW(), NOW()),
(212, 'DM', 'DMA', 'Dominica',NOW(), NOW()),
(214, 'DO', 'DOM', 'República Dominicana',NOW(), NOW()),
(218, 'EC', 'ECU', 'Ecuador',NOW(), NOW()),
(818, 'EG', 'EGY', 'Egipto',NOW(), NOW()),
(222, 'SV', 'SLV', 'El Salvador',NOW(), NOW()),
(784, 'AE', 'ARE', 'Emiratos Árabes Unidos',NOW(), NOW()),
(232, 'ER', 'ERI', 'Eritrea',NOW(), NOW()),
(703, 'SK', 'SVK', 'Eslovaquia',NOW(), NOW()),
(705, 'SI', 'SVN', 'Eslovenia',NOW(), NOW()),
(724, 'ES', 'ESP', 'España',NOW(), NOW()),
(581, 'UM', 'UMI', 'Islas ultramarinas de Estados Unidos',NOW(), NOW()),
(840, 'US', 'USA', 'Estados Unidos',NOW(), NOW()),
(233, 'EE', 'EST', 'Estonia',NOW(), NOW()),
(231, 'ET', 'ETH', 'Etiopía',NOW(), NOW()),
(234, 'FO', 'FRO', 'Islas Feroe',NOW(), NOW()),
(608, 'PH', 'PHL', 'Filipinas',NOW(), NOW()),
(246, 'FI', 'FIN', 'Finlandia',NOW(), NOW()),
(242, 'FJ', 'FJI', 'Fiyi',NOW(), NOW()),
(250, 'FR', 'FRA', 'Francia',NOW(), NOW()),
(266, 'GA', 'GAB', 'Gabón',NOW(), NOW()),
(270, 'GM', 'GMB', 'Gambia',NOW(), NOW()),
(268, 'GE', 'GEO', 'Georgia',NOW(), NOW()),
(239, 'GS', 'SGS', 'Islas Georgias del Sur y Sandwich del Sur',NOW(), NOW()),
(288, 'GH', 'GHA', 'Ghana',NOW(), NOW()),
(292, 'GI', 'GIB', 'Gibraltar',NOW(), NOW()),
(308, 'GD', 'GRD', 'Granada',NOW(), NOW()),
(300, 'GR', 'GRC', 'Grecia',NOW(), NOW()),
(304, 'GL', 'GRL', 'Groenlandia',NOW(), NOW()),
(312, 'GP', 'GLP', 'Guadalupe',NOW(), NOW()),
(316, 'GU', 'GUM', 'Guam',NOW(), NOW()),
(320, 'GT', 'GTM', 'Guatemala',NOW(), NOW()),
(254, 'GF', 'GUF', 'Guayana Francesa',NOW(), NOW()),
(324, 'GN', 'GIN', 'Guinea',NOW(), NOW()),
(226, 'GQ', 'GNQ', 'Guinea Ecuatorial',NOW(), NOW()),
(624, 'GW', 'GNB', 'Guinea-Bissau',NOW(), NOW()),
(328, 'GY', 'GUY', 'Guyana',NOW(), NOW()),
(332, 'HT', 'HTI', 'Haití',NOW(), NOW()),
(334, 'HM', 'HMD', 'Islas Heard y McDonald',NOW(), NOW()),
(340, 'HN', 'HND', 'Honduras',NOW(), NOW()),
(344, 'HK', 'HKG', 'Hong Kong',NOW(), NOW()),
(348, 'HU', 'HUN', 'Hungría',NOW(), NOW()),
(356, 'IN', 'IND', 'India',NOW(), NOW()),
(360, 'ID', 'IDN', 'Indonesia',NOW(), NOW()),
(364, 'IR', 'IRN', 'Irán',NOW(), NOW()),
(368, 'IQ', 'IRQ', 'Iraq',NOW(), NOW()),
(372, 'IE', 'IRL', 'Irlanda',NOW(), NOW()),
(352, 'IS', 'ISL', 'Islandia',NOW(), NOW()),
(376, 'IL', 'ISR', 'Israel',NOW(), NOW()),
(380, 'IT', 'ITA', 'Italia',NOW(), NOW()),
(388, 'JM', 'JAM', 'Jamaica',NOW(), NOW()),
(392, 'JP', 'JPN', 'Japón',NOW(), NOW()),
(400, 'JO', 'JOR', 'Jordania',NOW(), NOW()),
(398, 'KZ', 'KAZ', 'Kazajstán',NOW(), NOW()),
(404, 'KE', 'KEN', 'Kenia',NOW(), NOW()),
(417, 'KG', 'KGZ', 'Kirguistán',NOW(), NOW()),
(296, 'KI', 'KIR', 'Kiribati',NOW(), NOW()),
(414, 'KW', 'KWT', 'Kuwait',NOW(), NOW()),
(418, 'LA', 'LAO', 'Laos',NOW(), NOW()),
(426, 'LS', 'LSO', 'Lesotho',NOW(), NOW()),
(428, 'LV', 'LVA', 'Letonia',NOW(), NOW()),
(422, 'LB', 'LBN', 'Líbano',NOW(), NOW()),
(430, 'LR', 'LBR', 'Liberia',NOW(), NOW()),
(434, 'LY', 'LBY', 'Libia',NOW(), NOW()),
(438, 'LI', 'LIE', 'Liechtenstein',NOW(), NOW()),
(440, 'LT', 'LTU', 'Lituania',NOW(), NOW()),
(442, 'LU', 'LUX', 'Luxemburgo',NOW(), NOW()),
(446, 'MO', 'MAC', 'Macao',NOW(), NOW()),
(807, 'MK', 'MKD', 'ARY Macedonia',NOW(), NOW()),
(450, 'MG', 'MDG', 'Madagascar',NOW(), NOW()),
(458, 'MY', 'MYS', 'Malasia',NOW(), NOW()),
(454, 'MW', 'MWI', 'Malawi',NOW(), NOW()),
(462, 'MV', 'MDV', 'Maldivas',NOW(), NOW()),
(466, 'ML', 'MLI', 'Malí',NOW(), NOW()),
(470, 'MT', 'MLT', 'Malta',NOW(), NOW()),
(238, 'FK', 'FLK', 'Islas Malvinas',NOW(), NOW()),
(580, 'MP', 'MNP', 'Islas Marianas del Norte',NOW(), NOW()),
(504, 'MA', 'MAR', 'Marruecos',NOW(), NOW()),
(584, 'MH', 'MHL', 'Islas Marshall',NOW(), NOW()),
(474, 'MQ', 'MTQ', 'Martinica',NOW(), NOW()),
(480, 'MU', 'MUS', 'Mauricio',NOW(), NOW()),
(478, 'MR', 'MRT', 'Mauritania',NOW(), NOW()),
(175, 'YT', 'MYT', 'Mayotte',NOW(), NOW()),
(484, 'MX', 'MEX', 'México',NOW(), NOW()),
(583, 'FM', 'FSM', 'Micronesia',NOW(), NOW()),
(498, 'MD', 'MDA', 'Moldavia',NOW(), NOW()),
(492, 'MC', 'MCO', 'Mónaco',NOW(), NOW()),
(496, 'MN', 'MNG', 'Mongolia',NOW(), NOW()),
(500, 'MS', 'MSR', 'Montserrat',NOW(), NOW()),
(508, 'MZ', 'MOZ', 'Mozambique',NOW(), NOW()),
(104, 'MM', 'MMR', 'Myanmar',NOW(), NOW()),
(516, 'NA', ',NAM', ',Namibia',NOW(), NOW()),
(520, 'NR', ',NRU', ',Nauru',NOW(), NOW()),
(524, 'NP', ',NPL', ',Nepal',NOW(), NOW()),
(558, 'NI', ',NIC', ',Nicaragua',NOW(), NOW()),
(562, 'NE', ',NER', ',Níger',NOW(), NOW()),
(566, 'NG', ',NGA', ',Nigeria',NOW(), NOW()),
(570, 'NU', ',NIU', ',Niue',NOW(), NOW()),
(574, 'NF', ',NFK', 'Isla Norfolk',NOW(), NOW()),
(578, 'NO', ',NOR', ',Noruega',NOW(), NOW()),
(540, 'NC', ',NCL', ',Nueva Caledonia',NOW(), NOW()),
(554, 'NZ', ',NZL', ',Nueva Zelanda',NOW(), NOW()),
(512, 'OM', 'OMN', 'Omán',NOW(), NOW()),
(528, 'NL', ',NLD', 'Países Bajos',NOW(), NOW()),
(586, 'PK', 'PAK', 'Pakistán',NOW(), NOW()),
(585, 'PW', 'PLW', 'Palau',NOW(), NOW()),
(275, 'PS', 'PSE', 'Palestina',NOW(), NOW()),
(591, 'PA', 'PAN', 'Panamá',NOW(), NOW()),
(598, 'PG', 'PNG', 'Papúa Nueva Guinea',NOW(), NOW()),
(600, 'PY', 'PRY', 'Paraguay',NOW(), NOW()),
(604, 'PE', 'PER', 'Perú',NOW(), NOW()),
(612, 'PN', 'PCN', 'Islas Pitcairn',NOW(), NOW()),
(258, 'PF', 'PYF', 'Polinesia Francesa',NOW(), NOW()),
(616, 'PL', 'POL', 'Polonia',NOW(), NOW()),
(620, 'PT', 'PRT', 'Portugal',NOW(), NOW()),
(630, 'PR', 'PRI', 'Puerto Rico',NOW(), NOW()),
(634, 'QA', 'QAT', 'Qatar',NOW(), NOW()),
(826, 'GB', 'GBR', 'Reino Unido',NOW(), NOW()),
(638, 'RE', 'REU', 'Reunión',NOW(), NOW()),
(646, 'RW', 'RWA', 'Ruanda',NOW(), NOW()),
(642, 'RO', 'ROU', 'Rumania',NOW(), NOW()),
(643, 'RU', 'RUS', 'Rusia',NOW(), NOW()),
(732, 'EH', 'ESH', 'Sahara Occidental',NOW(), NOW()),
(90, 'SB', 'SLB', 'Islas Salomón',NOW(), NOW()),
(882, 'WS', 'WSM', 'Samoa',NOW(), NOW()),
(16, 'AS', 'ASM', 'Samoa Americana',NOW(), NOW()),
(659, 'KN', 'KNA', 'San Cristóbal y Nevis',NOW(), NOW()),
(674, 'SM', 'SMR', 'San Marino',NOW(), NOW()),
(666, 'PM', 'SPM', 'San Pedro y Miquelón',NOW(), NOW()),
(670, 'VC', 'VCT', 'San Vicente y las Granadinas',NOW(), NOW()),
(654, 'SH', 'SHN', 'Santa Helena',NOW(), NOW()),
(662, 'LC', 'LCA', 'Santa Lucía',NOW(), NOW()),
(678, 'ST', 'STP', 'Santo Tomé y Príncipe',NOW(), NOW()),
(686, 'SN', 'SEN', 'Senegal',NOW(), NOW()),
(891, 'CS', 'SCG', 'Serbia y Montenegro',NOW(), NOW()),
(690, 'SC', 'SYC', 'Seychelles',NOW(), NOW()),
(694, 'SL', 'SLE', 'Sierra Leona',NOW(), NOW()),
(702, 'SG', 'SGP', 'Singapur',NOW(), NOW()),
(760, 'SY', 'SYR', 'Siria',NOW(), NOW()),
(706, 'SO', 'SOM', 'Somalia',NOW(), NOW()),
(144, 'LK', 'LKA', 'Sri Lanka',NOW(), NOW()),
(748, 'SZ', 'SWZ', 'Suazilandia',NOW(), NOW()),
(710, 'ZA', 'ZAF', 'Sudáfrica',NOW(), NOW()),
(736, 'SD', 'SDN', 'Sudán',NOW(), NOW()),
(752, 'SE', 'SWE', 'Suecia',NOW(), NOW()),
(756, 'CH', 'CHE', 'Suiza',NOW(), NOW()),
(740, 'SR', 'SUR', 'Surinam',NOW(), NOW()),
(744, 'SJ', 'SJM', 'Svalbard y Jan Mayen',NOW(), NOW()),
(764, 'TH', 'THA', 'Tailandia',NOW(), NOW()),
(158, 'TW', 'TWN', 'Taiwán',NOW(), NOW()),
(834, 'TZ', 'TZA', 'Tanzania',NOW(), NOW()),
(762, 'TJ', 'TJK', 'Tayikistán',NOW(), NOW()),
(86, 'IO', 'IOT', 'Territorio Británico del Océano Índico',NOW(), NOW()),
(260, 'TF', 'ATF', 'Territorios Australes Franceses',NOW(), NOW()),
(626, 'TL', 'TLS', 'Timor Oriental',NOW(), NOW()),
(768, 'TG', 'TGO', 'Togo',NOW(), NOW()),
(772, 'TK', 'TKL', 'Tokelau',NOW(), NOW()),
(776, 'TO', 'TON', 'Tonga',NOW(), NOW()),
(780, 'TT', 'TTO', 'Trinidad y Tobago',NOW(), NOW()),
(788, 'TN', 'TUN', 'Túnez',NOW(), NOW()),
(796, 'TC', 'TCA', 'Islas Turcas y Caicos',NOW(), NOW()),
(795, 'TM', 'TKM', 'Turkmenistán',NOW(), NOW()),
(792, 'TR', 'TUR', 'Turquía',NOW(), NOW()),
(798, 'TV', 'TUV', 'Tuvalu',NOW(), NOW()),
(804, 'UA', 'UKR', 'Ucrania',NOW(), NOW()),
(800, 'UG', 'UGA', 'Uganda',NOW(), NOW()),
(858, 'UY', 'URY', 'Uruguay',NOW(), NOW()),
(860, 'UZ', 'UZB', 'Uzbekistán',NOW(), NOW()),
(548, 'VU', 'VUT', 'Vanuatu',NOW(), NOW()),
(862, 'VE', 'VEN', 'Venezuela',NOW(), NOW()),
(704, 'VN', 'VNM', 'Vietnam',NOW(), NOW()),
(92, 'VG', 'VGB', 'Islas Vírgenes Británicas',NOW(), NOW()),
(850, 'VI', 'VIR', 'Islas Vírgenes de los Estados Unidos',NOW(), NOW()),
(876, 'WF', 'WLF', 'Wallis y Futuna',NOW(), NOW()),
(887, 'YE', 'YEM', 'Yemen',NOW(), NOW()),
(262, 'DJ', 'DJI', 'Yibuti',NOW(), NOW()),
(894, 'ZM', 'ZMB', 'Zambia',NOW(), NOW()),
(716, 'ZW', 'ZWE', 'Zimbabue',NOW(), NOW());